"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PrivateRouteMiddleware from "@/components/auth/PrivateRouteMiddleware";
import { usePathname } from "next/navigation";
import SideBar from "@/components/layout/SideBar";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const noLayoutPaths = ["/auth/login", "/auth/register"];
  const hideLayout = noLayoutPaths.includes(pathname);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {hideLayout ? (
          <>{children}</>
        ) : (
          <PrivateRouteMiddleware requiredRole="ADMIN">
            <div className="flex max-lg:flex-col text-primaryBlack">
            <SideBar />
            <div className="flex-1">{children}</div>
          </div>
          </PrivateRouteMiddleware>
        )}
        <Toaster position="top-center" richColors/>
      </body>
    </html>
  );
}


// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
